### PR TITLE
Issue #3239420: Use composer-merge-plugin to manage project composer.json dependencies

### PR DESCRIPTION
**Pull request by mstenta**
See: https://www.drupal.org/project/farm/issues/3239420

### CODE REVIEW

**Review by symbioquine — COMMENTED** [review]
It looks like there are a couple things removed here that aren't added in https://github.com/farmOS/farmOS/pull/450/files - such as `authors` and `config.sort-packages`. Is that intentional? I'm not familiar with how those are used (other than what I could guess.)

**Comment by mstenta** [comment]
Good eye @symbioquine! That was intentional.

I decided to remove `authors` because it didn't seem like it was necessary to leave in for the template (presumably once deployed, someone else is maintaining that). Although I'm open to leaving it if there's a good reason to, or if that's standard practice. The Drupal `recommended-project` template does not include `authors`: https://github.com/drupal/recommended-project/blob/9.1.x/composer.json

As for `config.sort-packages` - I was being somewhat liberal in what I was removing from the project template, trying to par it down to bare essentials. It seems that `config.sort-packages` only really affects `composer require` behavior: https://getcomposer.org/doc/06-config.md#sort-packages

> `sort-packages`
> 
> Defaults to `false`. If `true`, the `require` command keeps packages sorted by name in `composer.json` when adding a new package.

This felt like fluff, and if a downstream maintainer wanted to add it they could, but I took it out just to omit everything but the essentials from our template. I don't really feel strongly either way, though, so if you think we should keep it that's fine with me.

**Comment by mstenta** [comment]
Also happy to split those removals out to separate commits to keep it clear.

**Comment by symbioquine** [comment]
Makes sense! I don't feel strongly about it needing a dedicated commit. Mostly just wanted it to be explicit somewhere since it wasn't mentioned in the issue or these pull requests (as far as I can see). If it ever comes up, your explanation above is probably plenty.

**Review by symbioquine — APPROVED** [review]

**Review by paul121 — APPROVED** [review]

**Comment by mstenta** [comment]
I went ahead and split the `authors` and `config.sort-packages` changes out to separate commits.

**Pull request merged**
