### PR TITLE
Add dependencies required to enable parallel unit tests via paratest

### PR DESCRIPTION
**Pull request by symbioquine**
Part of a larger change for https://www.drupal.org/project/farm/issues/3183682

### CODE REVIEW

**Comment by mstenta** [comment]
Thanks @symbioquine!

Curious to understand the `phpspec/prophecy-phpunit` dependency a bit more...

If I `grep` the `vendor` directory and Drupal `core` directory in the webroot I don't see any occurrences of `ProphecyTrait`.

I ran the `grep` after pulling in `brianium/paratest:^4`, so I don't think `paratest` depends on it either - although maybe I'm overlooking something.

I wonder if maybe you hit this error earlier because you were using `drupal/core-dev` 9.2.x at one point? I recall that from earlier conversations with you, and I see you fixed that with a workaround in https://github.com/farmOS/farmOS/pull/378/commits/c74d6ea41a42d9f9ede624e831a5be69e57b8c0b - so now it's not changing the `drupal/core-dev` dependency.

Maybe this `phpspec/prophecy-phpunit` dependency is left over from that?

The Drupal.org issue (https://www.drupal.org/project/drupal/issues/3182653) references the 9.1.x branch of Drupal, so maybe that is where this dependency is introduced.

I've never hit that error running tests myself - although I haven't tested running with `paratest` locally yet.

**Comment by symbioquine** [comment]
> I wonder if maybe you hit this error earlier because you were using `drupal/core-dev` 9.2.x at one point? I recall that from earlier conversations with you, and I see you fixed that with a workaround in [farmOS/farmOS@c74d6ea](https://github.com/farmOS/farmOS/commit/c74d6ea41a42d9f9ede624e831a5be69e57b8c0b) - so now it's not changing the `drupal/core-dev` dependency.
> 
> Maybe this `phpspec/prophecy-phpunit` dependency is left over from that?

I don't think so, but I'll test again...

**Comment by mstenta** [comment]
> Maybe this phpspec/prophecy-phpunit dependency is left over from that?

FYI we just ran into this upstream because Drupal 9.1.0 was released yesterday. It made me realize we had `^9.0.0` in our `composer.json` (for `drupal/core`, `drupal/core-dev`, and `drupal/core-composer-scaffold`) - which was allowing 9.1.0 to be included. I changed these to `~9.0.0` so that minor updates can be intentional moving forward.

**Comment by mstenta** [comment]
@symbioquine do you want to force push this without the `phpsec/prophecy-phpunit` part? That was included via https://github.com/farmOS/composer-project/commit/4742ed60dae9ded8fb4dff349b41f13fbe5f1e4d

**Comment by symbioquine** [comment]
Thanks for following up on this @mstenta but I don't think there's much point in proceeding here until I make some progress on https://github.com/farmOS/farmOS/pull/378 which is currently in my court - I still need to create that issue with Drupal Core...

**Comment by symbioquine** [comment]
Closing in favor of https://github.com/farmOS/composer-project/pull/2

**Pull request closed without merging**
